name: "Push documentation in /docs/wiki to GitHub wiki"

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push docs to wiki
        run: |-
          gh auth setup-git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git clone https://github.com/Point72/csp.wiki.git
          rm ./csp.wiki/*
          cp -r ./docs/wiki/* ./csp.wiki/
          cd csp.wiki
          git add -A
          git commit -m "Auto-update from /docs/wiki"
          git push --set-upstream origin
          rm -rf "flowerpot.wiki"
