name: "Generate openapi.json"

env:
  DEFAULT_PYTHON_VERSION: "3.12"

on:
  pull_request:
    paths: ['docs/**']

jobs:
  update-openapi-json:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update Home.md
        run: |-
          echo "testing" >> docs/Home.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update REST API documentation (openapi.json)'
          add: '*.md'
          push: true
